apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: talbovey-poi-map-app-dev
  annotations:
    argocd/app-name: talbovey-poi-map-app-dev
    backstage.io/kubernetes-id: talbovey-poi-map-app
    backstage.io/kubernetes-namespace: talbovey
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/talbovey-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/talbovey/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/talbovey/deployments/talbovey-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/talbovey-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://talbovey-poi-map-app-talbovey.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/talbovey"
  system: workshop-system-talbovey
  consumesApis:
    - gateway-api-talbovey
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-talbovey
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/talbovey"
